name: Build installar for supported os
on: push

jobs:
  build-app:
    strategy:
      matrix:
        os: [ macos-latest,ubuntu-20.04, windows-latest ]
    name: Build the application
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - run: ./gradlew package
      - run: mkdir staging && cp build/installer/* staging
      - name: upload build result
        uses: actions/upload-artifact@v2
        with:
          name: IRacing-Telemetry-${{matrix.os}}
          path: staging




